### PR TITLE
fix: disable menu plugin entries in cloud bpmn

### LINKED ISSUE #48: Menu Plugin Included in Camunda Cloud BPMN Tab
__Describe the Bug__

Even though Camunda Cloud BPMN plugins aren't supported the [menu](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/index.js#L7) and [style](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/index.js#L6) plugins are included regardless. When using the menu plugin there is an error since the bpmn-js plugin wasn't included.

wbs4j4rVJN

This isn't necessarily a bug but could also require a fix in the Camunda Modeler.

__Steps to Reproduce__

1. Install plugin
2. Create Camunda Cloud BPMN tab
3. Use menu plugin
4. Error in log

__Expected Behavior__

Menu plugin not included if Camunda Cloud BPMN tab.

__Environment__

- Library version: 0.15.0

### PR DESCRIPTION
**Pull request by Skaiir**
Depends on https://github.com/camunda/camunda-modeler/issues/2757

Closes #48

### CODE REVIEW

File: menu.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ module.exports = function(electronApp, menuState) {
     enabled: function() {
 
       // only enabled for BPMN diagrams
-      return menuState.bpmn && menuState.inactiveInput;
+      return menuState.bpmn && menuState.platform == 'platform' && menuState.inactiveInput;
```
Comment (nikku) [inline menu.js:10]: This is not backwards compatible.

Consider changing the check to `menuState.platform === 'cloud'`.

Comment (Skaiir) [reply menu.js:10]: Ah good point I hadn't considered the backwards compatibility requirements of plugins. Let me have a look on how I could change this.
